import type { CSSProperties } from 'react';

export const theme = {
  primary: '#b3006a',
  onPrimary: '#ffffff',
  background: '#f9f9ff',
  surface: '#ffffff',
  onSurface: '#151c27',
  onSurfaceVariant: '#5b3f49',
  outlineVariant: '#e3bdc8',
  outline: '#e3bdc8',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
};

export const S: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.background,
    padding: '24px',
    fontFamily: 'Arial, sans-serif',
    position: 'relative',
    overflow: 'hidden',
  },
  ambientGlow: {
    position: 'absolute',
    borderRadius: '50%',
    backgroundColor: theme.primary,
    opacity: 0.04,
    pointerEvents: 'none',
  },
  card: {
    backgroundColor: theme.surface,
    borderRadius: '24px',
    maxWidth: '420px',
    width: '100%',
    boxShadow: '0 4px 24px rgba(179,0,106,0.1)',
    border: `1px solid ${theme.outlineVariant}`,
    overflow: 'hidden',
    padding: '28px',
    position: 'relative',
  },
  stitchBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '4px',
    backgroundColor: theme.outlineVariant,
    opacity: 0.5,
  },
  lottieWrapper: {
    width: '90px',
    height: '90px',
    margin: '0 auto 12px',
  },
  title: {
    fontSize: '22px',
    fontWeight: 700,
    color: theme.primary,
    textAlign: 'center',
    marginBottom: '4px',
  },
  subtitle: {
    fontSize: '14px',
    color: theme.onSurfaceVariant,
    textAlign: 'center',
    marginBottom: '20px',
  },
  errorBox: {
    backgroundColor: theme.errorContainer,
    border: '1px solid rgba(186,26,26,0.3)',
    borderRadius: '10px',
    padding: '10px 14px',
    color: theme.onErrorContainer,
    fontSize: '13px',
    textAlign: 'center' as const,
    marginBottom: '14px',
  },
  label: {
    fontSize: '11px',
    fontWeight: 700,
    color: theme.onSurfaceVariant,
    letterSpacing: '0.6px',
    marginBottom: '5px',
    display: 'block',
  },
  input: {
    width: '100%',
    padding: '14px',
    fontSize: '14px',
    border: `1px solid ${theme.outline}`,
    borderRadius: '10px',
    outline: 'none',
    color: theme.onSurface,
    backgroundColor: theme.surface,
    boxSizing: 'border-box' as const,
    marginBottom: '14px',
  },
  button: {
    width: '100%',
    padding: '14px',
    backgroundColor: theme.primary,
    color: theme.onPrimary,
    border: 'none',
    borderRadius: '12px',
    fontSize: '15px',
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center' as const,
  },
  buttonDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  successContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.background,
    padding: '24px',
    fontFamily: 'Arial, sans-serif',
    textAlign: 'center' as const,
  },
  successCard: {
    backgroundColor: '#fff',
    borderRadius: '24px',
    padding: '40px 32px',
    maxWidth: '400px',
    width: '100%',
    boxShadow: '0 4px 24px rgba(179,0,106,0.1)',
    border: `1px solid ${theme.outlineVariant}`,
  },
  paw: {
    fontSize: '48px',
    margin: '0 0 12px',
  },
  successTitle: {
    fontSize: '24px',
    fontWeight: 700,
    color: theme.primary,
    margin: '0 0 12px',
  },
  successText: {
    fontSize: '15px',
    color: '#574146',
    lineHeight: 1.6,
    margin: '0 0 8px',
  },
  hint: {
    fontSize: '13px',
    color: '#8f6e79',
    margin: '8px 0 0',
  },
  brand: {
    fontSize: '12px',
    color: theme.onSurfaceVariant,
    textAlign: 'center' as const,
    marginTop: '20px',
    opacity: 0.6,
  },
};
