import type { CSSProperties } from 'react';

export const S: Record<string, CSSProperties> = {
  container: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f9f9ff',
    padding: '24px',
    fontFamily: 'Arial, sans-serif',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '24px',
    padding: '0',
    maxWidth: '420px',
    width: '100%',
    boxShadow: '0 4px 24px rgba(179,0,106,0.1)',
    border: '1px solid #e3bdc8',
    overflow: 'hidden',
  },
  cardHeader: {
    backgroundColor: '#b3006a',
    padding: '32px 28px',
    textAlign: 'center',
  },
  cardBody: {
    padding: '28px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  logo:        { fontSize: '52px', marginBottom: '12px' },
  title:       { fontSize: '22px', fontWeight: 700, color: '#fff', margin: 0 },
  subtitle:    { fontSize: '13px', color: 'rgba(255,255,255,0.75)', margin: '4px 0 0' },
  input: {
    width: '100%',
    padding: '14px 16px',
    fontSize: '15px',
    border: '1px solid #e3bdc8',
    borderRadius: '10px',
    outline: 'none',
    color: '#151c27',
    boxSizing: 'border-box',
  },
  button: {
    width: '100%',
    padding: '14px',
    backgroundColor: '#b3006a',
    color: '#ffffff',
    border: 'none',
    borderRadius: '10px',
    fontSize: '15px',
    fontWeight: 700,
    cursor: 'pointer',
  },
  buttonDisabled: {
    opacity: 0.7,
    cursor: 'not-allowed',
  },
  errorBox: {
    backgroundColor: '#ffdad6',
    border: '1px solid rgba(186,26,26,0.3)',
    borderRadius: '10px',
    padding: '12px 14px',
    color: '#93000a',
    fontSize: '14px',
  },
  successContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f9f9ff',
    padding: '24px',
    fontFamily: 'Arial, sans-serif',
    textAlign: 'center',
  },
  successCard: {
    backgroundColor: '#fff',
    borderRadius: '24px',
    padding: '40px 32px',
    maxWidth: '400px',
    width: '100%',
    boxShadow: '0 4px 24px rgba(179,0,106,0.1)',
    border: '1px solid #e3bdc8',
  },
  successIcon:  { fontSize: '64px', marginBottom: '16px' },
  successTitle: { fontSize: '24px', fontWeight: 700, color: '#b3006a', margin: '0 0 12px' },
  successText:  { fontSize: '15px', color: '#574146', lineHeight: 1.6, margin: '0 0 8px' },
  hint:         { fontSize: '13px', color: '#8f6e79', margin: '8px 0 0' },
  label: {
    fontSize: '11px',
    fontWeight: 700,
    color: '#5b3f49',
    letterSpacing: '0.5px',
    marginBottom: '-4px',
  },
};